# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b454c4961df966b6578e68112991f2a127319a1148d1ee7213aae02f8d38e76ab5b00f02831d0768c5c5ad00f281928fb068d947ab35691883ceb5db14a35cad

test:
  secret_key_base: 0d6297b4d08ad6dd4e5f9b016081cc5b54e6a2a7f1d1437e65c73d35b680257404fbfdff622e91f204be06df69e29dd490d8bcffee790cbd153273ce60622299

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: b454c4961df966b6578e68112991f2a127319a1148d1ee7213aae02f8d38e76ab5b00f02831d0768c5c5ad00f281928fb068d947ab35691883ceb5db14a35cad